### ISSUE TITLE
How the heck do I use this?

### ISSUE THREAD

**Issue by EnderDev** [szdc/tiktok-api#90]
Hello, I'm trying to make it so you can type in `!tiktok <search string>`, and it will return the direct video url.  https://hasteb.in/juricefe.js

I just keep getting this error:
```C:\Users\Administrator\Desktop\Ender\Ender>node --experimental-modules bot.js
(node:7384) ExperimentalWarning: The ESM module loader is experimental.
C:\Users\Administrator\Desktop\Ender\Ender\commands\tiktok.js:1
(function (exports, require, module, __filename, __dirname) { import TikTokAPI, { getRequestParams } from 'tiktok-api';
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Proxy.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)```

**Comment by Pilfer** [comment]
Looks like

```
import TikTokAPI, { getRequestParams } from 'tiktok-api';
```

needs to be

```
import { TikTokAPI, getRequestParams } from 'tiktok-api';
```

**Comment by folt** [comment]
I have the same problem

**Comment by PJ-G** [comment]
Is this issue resolved?

**Comment by EnderDev** [comment]
Yup.
